name: Question
description: Ask us a question about TerraCraft
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Ask your question here:
    validations:
      required: true
