name: Question
description: Ask us a question about TerraCraft
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Ask your question here
      description: Make sure to provide all necessary information.
    validations:
      required: true
